server:
  port: 8083

spring:
  cloud:
    gateway:
      routes:
      - id: accountModule
        uri: http://localhost:8081/
        predicates:
        - Path=/accounts/**
      - id: loanModule
        uri: http://localhost:8082/
        predicates:
        - Path=/loans/**
      - id: EmployeeModule
        uri: http://localhost:8084/
        predicates:
        - Path=/employees/**
      - id: UserModule
        uri: http://localhost:8090/
        predicates:
        - Path=/user/**        